replicaCount: 1

image:
  repository: 130830900133.dkr.ecr.ap-northeast-1.amazonaws.com/java-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: JAVA_ENV
    value: production

# Use TCP probe instead of HTTP since the app has no health endpoint
livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

nodeSelector: {}

tolerations: []
affinity: {}
