name: Build & Deploy Node API to ECR

on:
  push:
    paths:
      - 'node-api/**'
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
      ECR_REPOSITORY: node-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Tag Docker Image
        run: |
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${ECR_REPOSITORY}
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t $ECR_URI:$IMAGE_TAG node-api
          docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest

      - name: Push Docker Image to ECR
        run: |
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${ECR_REPOSITORY}
          IMAGE_TAG=${GITHUB_SHA}
          docker push $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:latest
