name: Build & Push Docker Image (Java App)

on:
  workflow_run:
    workflows: ["SAST Scan for Java App"]  
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
      ECR_REPOSITORY: java-api   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image
        run: |
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${ECR_REPOSITORY}
          IMAGE_TAG=${{ github.sha }}
          echo "Building and pushing image: $ECR_URI:$IMAGE_TAG"

          # Build image from java-app/ directory
          docker build -t $ECR_URI:$IMAGE_TAG java-app

          # Push only commit SHA tag
          docker push $ECR_URI:$IMAGE_TAG
