name: Deploy Node API to EKS

on:
  workflow_dispatch:
    inputs:
      image_tag: latest
        description: 'Docker image tag to deploy (commit SHA)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
      ECR_REPOSITORY: node-api
      HELM_CHART_PATH: helm/node-api
      K8S_NAMESPACE: default

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: '1.28.0'

      - name: Update kubeconfig
        run: |
          aws eks --region ${AWS_REGION} update-kubeconfig --name eks-cluster

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Deploy Node API via Helm
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${ECR_REPOSITORY}
          helm upgrade --install node-api ${HELM_CHART_PATH} \
            --namespace ${K8S_NAMESPACE} --create-namespace \
            --set image.repository=$IMAGE_URI \
            --set image.tag=${{ github.event.inputs.image_tag }}
