name: SAST Scan for Java App

on:
  push:
    paths:
      - "java-app/**"
  workflow_dispatch:

jobs:
  codeql:
    name: CodeQL SAST
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          queries: security-extended

      # Manually compile the Java sources
      - name: Build with javac
        run: |
          cd java-app
          mkdir -p build
          javac -cp "src/main/webapp/WEB-INF/lib/*" \
            -d build \
            $(find src/main/java -name "*.java")

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
