name: Terraform Network

on:
  push:
    branches: [main]
    paths:
      - 'terraform/module/network_skeleton/**'
      - 'terraform/wrapper/network_skeleton/**'
      - 'terraform/module/compute/**'
      - 'terraform/wrapper/compute/**'
      - 'terraform/module/rds/**'
      - 'terraform/wrapper/rds/**'

jobs:
  terraform-network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Checkov on Network module
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/module/network_skeleton

      - name: Run Checkov on Network wrapper
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/wrapper/network_skeleton

      - name: Terraform Init
        working-directory: terraform/wrapper/network_skeleton
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/wrapper/network_skeleton
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/wrapper/network_skeleton
        run: terraform apply -auto-approve
