name: Network Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/wrapper/network_skeleton/**'
      - 'terraform/wrapper/compute/**'
      - 'terraform/wrapper/rds/**'
  workflow_dispatch:

jobs:
  network:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/wrapper/network_skeleton

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .

      - run: terraform plan -out=tfplan
      - if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
