name: Terraform RDS

on:
  workflow_run:
    workflows: ["Terraform Compute"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to run (apply or destroy)'
        required: true
        default: 'apply'

jobs:
  terraform-rds:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: terraform/wrapper/rds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Checkov on RDS module
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/module/rds

      - name: Run Checkov on RDS wrapper
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/wrapper/rds

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' && github.ref == 'refs/heads/main' }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' && github.ref == 'refs/heads/main' }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
