name: RDS Terraform

on:
  workflow_run:
    workflows: ["Compute Terraform"]
    types:
      - completed
  workflow_dispatch:

jobs:
  rds:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: terraform/wrapper/rds

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate

      # ✅ Checkov Scan
      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .

      - run: terraform plan -out=tfplan
      - if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
